[package]
name = "attestation-daemon"
version = "0.1.0"
authors = ["LKatalin"]
edition = "2018"

[dependencies]
openssl = "0.10.23"
signatory-ring = "0.12.0"
signatory = "0.12.0"
dcap-ql = { path = "../../rust-sgx/dcap-ql" }
"sgx-isa" = { version = "0.3.0", path = "../../rust-sgx/sgx-isa" }
